function coeffs_j_opt = coeffs_j_opt(t,in2)
%COEFFS_J_OPT
%    COEFFS_J_OPT = COEFFS_J_OPT(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    01-Dec-2025 14:02:16

c4 = in2(:,4);
c5 = in2(:,5);
c6 = in2(:,6);
coeffs_j_opt = c4+c5.*t+(c6.*t.^2)./2.0;
end
