function coeffs_a_opt = coeffs_a_opt(t,in2)
%COEFFS_A_OPT
%    COEFFS_A_OPT = COEFFS_A_OPT(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    02-Dec-2025 13:33:10

c3 = in2(:,3);
c4 = in2(:,4);
c5 = in2(:,5);
c6 = in2(:,6);
coeffs_a_opt = c3+c4.*t+(c5.*t.^2)./2.0+(c6.*t.^3)./6.0;
end
