function final_opt_vel_j0_pass_var = final_opt_vel_j0_pass(v0,a0,j0,af,sf,T)
%FINAL_OPT_VEL_J0_PASS
%    FINAL_OPT_VEL_J0_PASS_VAR = FINAL_OPT_VEL_J0_PASS(V0,A0,J0,AF,SF,T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    27-Nov-2025 13:20:29

t2 = T.^2;
final_opt_vel_j0_pass_var = ((sf.*-6.0e+1+T.*v0.*3.6e+1+a0.*t2.*9.0-af.*t2.*3.0+T.^3.*j0).*(-1.0./2.4e+1))./T;
end
