function out1 = final_opt_time_stop_j0(v0,a0)
%FINAL_OPT_TIME_STOP_J0
%    OUT1 = FINAL_OPT_TIME_STOP_J0(V0,A0)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    02-Dec-2025 13:33:20

out1 = (v0.*-2.0)./a0;
end
