function out1 = time_min_vel(a0,sf)
%TIME_MIN_VEL
%    OUT1 = TIME_MIN_VEL(A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    02-Dec-2025 13:24:29

out1 = sqrt(1.5e+1).*sf.*1.0./sqrt(-a0.*sf);
end
